default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: ''
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: muraqiita_development

test:
  <<: *default
  database: muraqiita_test

production:
  <<: *default
  database: muraqiita_production
  username: root
  password: ''
